### ISSUE TITLE
logic area

### ISSUE THREAD

**Issue by shanshuixiangyi** [ZcashFoundation/zcash-fpga#18]
Using logic registers to do these algorithms. It consumes too much resources registers and LUTs. 
Why don't you use the memory method(such as internal or external RAMS) to implement these algorithms?It will reduce a lot of resources cells.

**Comment by bsdevlin** [comment]
In this case we didn't really approach the fpga limit on FFs, only LUTs I
think were high. But most of the LUTs are used in the multiplexing and
formula calculation.

You could operate on a small bit width and use RAM to store intermediate
results but it would impact your performance.
