### ISSUE TITLE
Build test application got error

### ISSUE THREAD

**Issue by LeonMac** [ZcashFoundation/zcash-fpga#5]
I build the AFI on one Centos machine successfully. 
I am able to load AFI to another F1 instance (ubuntu machine) successfully.
When I am trying to build the application to call-up the AFI, meet such issue (on ubuntu F1 machine):
Please have a look?

`ubuntu@ip-XXXXXXXXX~/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime$ make all
gcc -DCONFIG_LOGLEVEL=4 -g -Wall -I/home/ubuntu/aws-fpga/sdk/userspace/include -I /home/ubuntu/aws-fpga/hdk/common/software/include -I ./include -lstdc++ -std=c++11 -o test_zcash zcash_fpga.cpp test_zcash.cpp /home/ubuntu/aws-fpga/sdk/userspace/utils/sh_dpi_tasks.o  -lfpga_mgmt -lrt -lpthread
/tmp/ccjfM665.o: In function `zcash_fpga::get_instance()':
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/zcash_fpga.cpp:28: undefined reference to `__cxa_guard_acquire'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/zcash_fpga.cpp:28: undefined reference to `__cxa_guard_release'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/zcash_fpga.cpp:28: undefined reference to `__cxa_guard_abort'
/tmp/ccjfM665.o:(.data.rel.local.DW.ref.__gxx_personality_v0[DW.ref.__gxx_personality_v0]+0x0): undefined reference to `__gxx_personality_v0'
/tmp/ccynn5Cx.o: In function `string_to_hex(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)':
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:66: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::length() const'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:68: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const'
/tmp/ccynn5Cx.o: In function `main':
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:118: undefined reference to `std::allocator<char>::allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:118: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:118: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:118: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:119: undefined reference to `std::allocator<char>::allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:119: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:119: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:119: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:120: undefined reference to `std::allocator<char>::allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:120: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:120: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:120: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:121: undefined reference to `std::allocator<char>::allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:121: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:121: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:121: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:122: undefined reference to `std::allocator<char>::allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:122: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:122: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:122: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:179: undefined reference to `std::allocator<char>::allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:179: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:179: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:179: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:185: undefined reference to `std::allocator<char>::allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:185: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:185: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:185: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:191: undefined reference to `std::allocator<char>::allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:191: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:191: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:191: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:197: undefined reference to `std::allocator<char>::allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:197: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:197: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:197: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:203: undefined reference to `std::allocator<char>::allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:203: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:203: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:203: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:209: undefined reference to `std::allocator<char>::allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:209: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:209: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:209: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:328: undefined reference to `std::allocator<char>::allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:328: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:328: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:328: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:329: undefined reference to `std::allocator<char>::allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:329: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:329: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:329: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:330: undefined reference to `std::allocator<char>::allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:330: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:330: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:330: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:331: undefined reference to `std::allocator<char>::allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:331: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:331: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:331: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:332: undefined reference to `std::allocator<char>::allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:332: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:332: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:332: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:333: undefined reference to `std::allocator<char>::allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:333: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:333: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:333: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:334: undefined reference to `std::allocator<char>::allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:334: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:334: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:334: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:335: undefined reference to `std::allocator<char>::allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:335: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:335: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:335: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:336: undefined reference to `std::allocator<char>::allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:336: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:336: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:336: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:337: undefined reference to `std::allocator<char>::allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:337: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:337: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:337: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:338: undefined reference to `std::allocator<char>::allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:338: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:338: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:338: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:339: undefined reference to `std::allocator<char>::allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:339: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:339: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:339: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:118: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:119: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:120: undefined reference to `std::allocator<char>::~allocator()'
/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:121: undefined reference to `std::allocator<char>::~allocator()'
/tmp/ccynn5Cx.o:/home/ubuntu/aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime/test_zcash.cpp:122: more undefined references to `std::allocator<char>::~allocator()' follow
collect2: error: ld returned 1 exit status
Makefile:34: recipe for target 'test_zcash' failed
make: *** [test_zcash] Error 1
`

**Comment by bsdevlin** [comment]
Have you ran "source sdk_setup.sh" from the base aws directory? Also when I make I only run "make all", is that how you are doing it?

**Comment by LeonMac** [comment]
1. Yes I had the "source sdk_setup.sh" before the make. The setup is OK without error reported.
source hdk_setup.sh can not be sucessful as this F1 instance does not have Vivado installed.. that is one of my local region issue, aws did not give good solution yet..

```
ubuntu@ip-XXXXXXXXX:~/aws-fpga$ source sdk_setup.sh
INFO: Setting up environment variables
<.....omit a lot of log here.....>
AWS FPGA: Done with Amazon FPGA Image (AFI) Management Tools install.
Done with SDK install.
INFO: sdk_setup.sh PASSED
```
2. Yes the above error happen after key in "make all" (which I did not paste in).

I think one big different is I am doing the Host app build on different machine (a ubuntu machine)?

**Comment by bsdevlin** [comment]
Yeah it might be because the machine is different. Are you able to confirm the other example designs can compile? E.g. cl_hello_world also has a program you can try making (you can try this without building the FPGA image)
https://github.com/aws/aws-fpga/tree/master/hdk/cl/examples/cl_hello_world/software/runtime

If the program in there also doesn't work its probably something you can ask AWS to fix.

**Comment by LeonMac** [comment]
Yes the helloworld can be compiled correctly and AFI can be called correctly on this F1 ubuntu machine..

**Comment by LeonMac** [comment]
The error log is typically something like "undefined reference to ..." would that due to some library missing?

**Comment by bsdevlin** [comment]
I did need to use c++ so I have this in the Makefile  CFLAGS:     -lstdc++ -std=c++11
Maybe it's something to do with builder options or version of gcc?

I can keep trying to debug and let you know if I find something.

**Comment by LeonMac** [comment]
tks so much.. I will try to dig something as well.. btw we will have a long vacation in China for next week,  so response will be slow.
Thanks a lot for the help.

**Comment by LeonMac** [comment]
Had been working on some other stuff for days, just back to this issue, these are my finding:
1. Try re-build cl_hello_world example, it works fine but as it is c program, so makefile does not contain -lstdc++ -std=c++11; looks not helpful.
2. checked the gcc version is 7.4.0;
3. Then in makefile simply change the CC from gcc to g++, and comments out the  -lstdc++ -std=c++11; then build passed without error report -- let me know if this is align your expect?

Today I have no time and tomorrow I will find time to try load AFI to do the follow up test.

**Comment by bsdevlin** [comment]
I'm actually traveling right now so a bit hard for me to confirm, but if
it's building without error then that is probably right (I'll check when
I'm back in front of a computer). Let me know how the AFI test goes.
