### ISSUE TITLE
Follow up the g++ compiled test program, AFI detection error.

### ISSUE THREAD

**Issue by LeonMac** [ZcashFoundation/zcash-fpga#6]
Hi I run the test code but reported as no AFI detected. 
1. however check manually by I do have the AFI loaded correctly, slot/VendorID/DeviceId shall be all right (see log below)--anything else could cause error?
The error comes from this function: fpga_mgmt_describe_local_image() --but can not find its implementation.
2. log INFO shows the all tests passed--but the tests did not run yet?
3. switch to root by su command and run, same error.

`ubuntu@ip-XXXXXXXXX: ~ /aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime$ make all
g++ -DCONFIG_LOGLEVEL=4 -g -Wall -I /home/ubuntu/aws-fpga/sdk/userspace/include -I /home/ubuntu/aws-fpga/hdk/common/software/include -I ./include -lstdc++ -std=c++11 -o test_zcash zcash_fpga.cpp test_zcash.cpp /home/ubuntu/aws-fpga/sdk/userspace/utils/sh_dpi_tasks.o  -lfpga_mgmt -lrt -lpthread

ubuntu@ip-XXXXXXXXX:~ /aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime$ sudo ./test_zcash 
2019-10-10T02:29:23.142966Z, undefined, ERROR, zcash_fpga.cpp +153: check_afi_ready(): ERROR: Unable to get AFI information from slot 0. Are you running as root?
2019-10-10T02:29:23.143041Z, undefined, ERROR, zcash_fpga.cpp +47: init_fpga(): ERROR: AFI not ready
ERROR: Unable to initialize to FPGA!
INFO: All tests passed!

ubuntu@ip-XXXXXXXXX:~ /aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime$  sudo fpga-describe-local-image -S 0 -R -H
Type  FpgaImageSlot  FpgaImageId             StatusName    StatusCode   ErrorName    ErrorCode   ShVersion
AFI          0       agfi-0ea41d448d4efefb7  loaded            0        ok               0       0x04261818
Type  FpgaImageSlot  VendorId    DeviceId    DBDF
AFIDEVICE    0       0x1d0f      0xf000      0000:00:1d.0
`

**Comment by bsdevlin** [comment]
Can you paste the print out when you load the AFI?
`sudo fpga-load-local-image -S 0 -I -F xxxx`
And does this command run OK, no errors?
`sudo fpga-describe-local-image -S 0 --metrics`

**Comment by LeonMac** [comment]
OK run fpga-describe-local-image with -F flag return error.
Check help -F means force-shell-reload, does that imply this F1 instance need some extra driver to be installed?
Also pasted the --metrics result FYI.

> ubuntu@ip:~ /aws-fpga$ sudo fpga-describe-local-image -S 0
AFI          0       none                    cleared           1        ok               0       0x071417d3
AFIDEVICE    0       0x1d0f      0x1042      0000:00:1d.0
ubuntu@ip:~ /aws-fpga$ sudo fpga-load-local-image -S 0 -H -I -F agfi-0ea41d448d4efefb7
Error: (5) invalid-afi-id
The agfi id passed is invalid or you do not have permission to load
the AFI.
ubuntu@ip:~ /aws-fpga$ sudo fpga-load-local-image -S 0 -H -I agfi-0ea41d448d4efefb7
Type  FpgaImageSlot  FpgaImageId             StatusName    StatusCode   ErrorName    ErrorCode   ShVersion
AFI          0       agfi-0ea41d448d4efefb7  loaded            0        ok               0       0x04261818
Type  FpgaImageSlot  VendorId    DeviceId    DBDF
AFIDEVICE    0       0x1d0f      0xf000      0000:00:1d.0

ubuntu@ip:~/aws-fpga$ sudo fpga-describe-local-image -S 0 --metrics
AFI          0       agfi-0ea41d448d4efefb7  loaded            0        ok               0       0x04261818
AFIDEVICE    0       0x1d0f      0xf000      0000:00:1d.0
sdacl-slave-timeout=0
virtual-jtag-slave-timeout=0
ocl-slave-timeout=0
bar1-slave-timeout=0
dma-pcis-timeout=0
pcim-range-error=0
pcim-axi-protocol-error=0
pcim-axi-protocol-4K-cross-error=0
pcim-axi-protocol-bus-master-enable-error=0
pcim-axi-protocol-request-size-error=0
pcim-axi-protocol-write-incomplete-error=0
pcim-axi-protocol-first-byte-enable-error=0
pcim-axi-protocol-last-byte-enable-error=0
pcim-axi-protocol-bready-error=0
pcim-axi-protocol-rready-error=0
pcim-axi-protocol-wchannel-error=0
sdacl-slave-timeout-addr=0x0
sdacl-slave-timeout-count=0
virtual-jtag-slave-timeout-addr=0x0
virtual-jtag-slave-timeout-count=0
ocl-slave-timeout-addr=0x0
ocl-slave-timeout-count=0
bar1-slave-timeout-addr=0x0
bar1-slave-timeout-count=0
dma-pcis-timeout-addr=0x0
dma-pcis-timeout-count=0
pcim-range-error-addr=0x0
pcim-range-error-count=0
pcim-axi-protocol-error-addr=0x0
pcim-axi-protocol-error-count=0
pcim-write-count=0
pcim-read-count=0
DDR0
   write-count=0
   read-count=0
DDR1
   write-count=0
   read-count=0
DDR2
   write-count=0
   read-count=0
DDR3
   write-count=0
   read-count=0
Clock Group A Frequency (Mhz)
125  62  187  250  
Clock Group B Frequency (Mhz)
125  62  
Clock Group C Frequency (Mhz)
300  400  
Power consumption (Vccint):
   Last measured: 0 watts
   Average: 0 watts
   Max measured: 0 watts
Cached agfis:
   agfi-0ea41d448d4efefb7

**Comment by bsdevlin** [comment]
Yes I had to use force reload because there was a known issue on AWS where
you have to load the image twice (first load has issues), not sure if this
is still a bug or not.

It looks like the load is failing "The agfi id passed is invalid or you do
not have permission to load the AFI."

Are you able to run this command and see if there are any problems with the
AFI you created? (need to use AFI id, not global id)

 aws ec2 describe-fpga-images --fpga-image-ids xxxx

**Comment by LeonMac** [comment]
ubuntu@ip-XX:~/aws-fpga$ aws ec2 describe-fpga-images --fpga-image-ids afi-0b0a2788abf477b80
{
    "FpgaImages": [
        {
            "FpgaImageId": "afi-0b0a2788abf477b80",
            "FpgaImageGlobalId": "agfi-0ea41d448d4efefb7",
            "Name": "liangma-zcash-fpga",
            "Description": "zcash-afi",
            "ShellVersion": "0x04261818",
            "PciId": {
                "DeviceId": "0xf000",
                "VendorId": "0x1d0f",
                "SubsystemId": "0x1d51",
                "SubsystemVendorId": "0xfedd"
            },
            "State": {
                "Code": "available"
            },
            "CreateTime": "2019-09-30T02:30:29.000Z",
            "UpdateTime": "2019-09-30T03:19:45.000Z",
            "OwnerId": "323020277049",
            "Tags": [],
            "Public": false
        }
    ]
}

**Comment by LeonMac** [comment]
Can you suggest where can I modify the code locally that I can do fpga load without -F? so this may bypass this issue?

**Comment by bsdevlin** [comment]
The issue for the -F is here: https://forums.aws.amazon.com/thread.jspa?threadID=278656 
It was a AWS issue so I don't know if it has already been resolved, but last time I check it hadn't been.

This issue:
ubuntu@ip:~ /aws-fpga$ sudo fpga-load-local-image -S 0 -H -I -F agfi-0ea41d448d4efefb7
Error: (5) invalid-afi-id
The agfi id passed is invalid or you do not have permission to load

I'm not sure about, the describe-fpga-images commands seems to run correctly, if you take the -F out does it work?

Just check that running `sudo fpga-describe-local-image -S 0 --metrics `  shows 0 for this line: `ocl-slave-timeout-addr` if you run it without -F

**Comment by LeonMac** [comment]
1. Yes, without -F it works well (see log in 1st comments of this thead), anyway I pasted here:
`ubuntu@ip-XXXXXXXXX:~ /aws-fpga/hdk/cl/developer_designs/cl_zcash/software/runtime$ sudo fpga-describe-local-image -S 0 -R -H
Type FpgaImageSlot FpgaImageId StatusName StatusCode ErrorName ErrorCode ShVersion
AFI 0 agfi-0ea41d448d4efefb7 loaded 0 ok 0 0x04261818
Type FpgaImageSlot VendorId DeviceId DBDF
AFIDEVICE 0 0x1d0f 0xf000 0000:00:1d.0`

2. running sudo fpga-describe-local-image -S 0 --metrics
ocl-slave-timeout-addr=0x0  //this means no error happen, so no reload concern?

**Comment by bsdevlin** [comment]
Yes that seems ok (does the test program run OK)?

**Comment by bsdevlin** [comment]
I just checked and it is just the location of the F flag that is a problem, can you run:
`sudo fpga-load-local-image -S 0 -H -I agfi-0ea41d448d4efefb7 -F`
But I think the -F flag shouldn't matter to actually detecting the AFI is loaded (the error from test program), just to check I also tried making your other changes (gcc to g++ and deleted those flags), and I get a lot of warnings but the test program still runs.

If the -F flag dosen't change things, can you try running the hello world program? It should also try to detect the AFI at start (and then probably fail later on in a separate test). Just to check if it is an issue with loading the AFI on AWS's side or not.

**Comment by bsdevlin** [comment]
Let me know if the hello world program works on the Zcash FPGA image (at
least loading the AFI), then we can at least tell it is an issue with the
test program and I can try think of what might be the problem. If the hello
world program won't load the Zcash AFI it might be best to raise it as an
issue with AWS or on the AWS forums as I can't think of why a AFI wouldn't
be able to load (maybe some issue with AWS script creating the AFI).

**Comment by LeonMac** [comment]
just tested:
1st time occasionally, I run helloworld without sudo, have the same error reported.
2nd run helloworld with sudo,  the helloworld runs correctly.

Note for your test program, I do use the sudo.
`
ubuntu@ip-:~ /aws-fpga/hdk/cl/examples/cl_hello_world/software/runtime$ ./test_hello_world 
2019-10-11T09:53:02.629981Z, undefined, ERROR, test_hello_world.c +183: check_afi_ready(): Unable to get AFI information from slot 0. Are you running as root?
2019-10-11T09:53:02.630024Z, undefined, ERROR, test_hello_world.c +132: main(): AFI not ready
ubuntu@ip-172-31-22-109:~ /aws-fpga/hdk/cl/examples/cl_hello_world/software/runtime$ sudo ./test_hello_world 
AFI PCI  Vendor ID: 0x1d0f, Device ID 0xf000
===== Starting with peek_poke_example =====
-------- delete many logs here ------
ubuntu@ip:~/aws-fpga/hdk/cl/examples/cl_hello_world/software/runtime$ 

`

**Comment by LeonMac** [comment]
I just did such a quick test:
1. load the helloword AFI, and run the helloworld test program, test passed:
` sudo ./test_hello_world 
AFI PCI  Vendor ID: 0x1d0f, Device ID 0xf000
===== Starting with peek_poke_example =====
Writing 0xefbeadde to HELLO_WORLD register (0x0000000000000500)
=====  Entering peek_poke_example =====
register: 0xdeadbeef
TEST PASSEDResulting value matched expected value 0xdeadbeef. It worked!
`
2. Then I load my zcash-fpga AFI, and run the helloworld test program again, test failed:
`sudo ./test_hello_world 
AFI PCI  Vendor ID: 0x1d0f, Device ID 0xf000
===== Starting with peek_poke_example =====
Writing 0xefbeadde to HELLO_WORLD register (0x0000000000000500)
=====  Entering peek_poke_example =====
register: 0x400000
TEST FAILEDResulting value did not match expected value 0xdeadbeef. Something didn't work.`

3. then run th test_zcash program:
`sudo ./test_zcash 
2019-10-11T11:06:34.885050Z, undefined, ERROR, zcash_fpga.cpp +153: check_afi_ready(): ERROR: Unable to get AFI information from slot 0. Are you running as root?
2019-10-11T11:06:34.885120Z, undefined, ERROR, zcash_fpga.cpp +47: init_fpga(): ERROR: AFI not ready
ERROR: Unable to initialize to FPGA!
INFO: All tests passed!
`

The 2nd test failed is totally reasonable as the zcash-fpga AFI does not match with the helloword test program. 

But compare the 2nd and 3rd log, that imply by using helloworld test program, it indeed passed the AFI detection and does not complain the AFI uncorrect.

**Comment by bsdevlin** [comment]
Thanks - so to confirm it looks like something about the test program
(maybe not the AFI) that has a problem?

**Comment by LeonMac** [comment]
I tend to believe this is not AFI issue, but the test_zcash program parse AFI issue.
my small two cents:
1. I compare the test code  with helloworld and looks for AFI parsing you made some modification that to define the check_afi_ready() inside zcash_fpga as private... I am not familiar to c++, just wondering if that could cause privilege relevant issue.
2. Another concern is you are running in CENTOS and I am running in UBUNTU.

**Comment by LeonMac** [comment]
I don't think comment out the AFI check is a good idea, but it works on my test (because my AFI loaded correctly).
I did a little more debug, it seems inside int zcash_fpga::check_afi_ready(), fpga_mgmt_describe_local_image() routine return invalid information:
`slot_id=0 
INFO: AFI PCI  Vendor ID: 0x0, Device ID 0x0
INFO: AFI does not show expected PCI vendor id and device ID. If the AFI was just loaded, it might need a rescan. Rescanning now.
2019-10-12T10:25:51.411900Z, undefined, ERROR, zcash_fpga.cpp +176: check_afi_ready(): ERROR: Unable to get AFI information from slot 0
2019-10-12T10:25:51.411949Z, undefined, ERROR, zcash_fpga.cpp +48: init_fpga(): ERROR: AFI not ready
`

**Comment by bsdevlin** [comment]
Ok thanks - that's good to know about. So after that fix / removing the check(), the test passes?

**Comment by LeonMac** [comment]
Yes the test run correctly and also no more AFI detection error happen. Output is as same as in your document.
