### ISSUE TITLE
scan mode

### ISSUE THREAD

**Issue by shanshuixiangyi** [ZcashFoundation/zcash-fpga#7]
Hi ,,, 
I  find this code do not have enter into scan mode. I will use uvm method to verification some code of the project to make it to ASIC. Does the code have finished ?

**Comment by bsdevlin** [comment]
Hi, what do you mean by scan mode?
Yes the code is finished.

**Comment by shanshuixiangyi** [comment]
This URL as follows introduce the mode.
https://anysilicon.com/overview-and-dynamics-of-scan-testing/ 
I am studying your code.It's very nice.I should learn more about math to understand the code.

**Comment by bsdevlin** [comment]
I didn't add any scan chains like that, because this project was targeting a FPGA I didn't need to. But if you want to target an ASIC you would need to add it.
