### ISSUE TITLE
Maximum prover throughput

### ISSUE THREAD

**Issue by jon-chuang** [ZcashFoundation/zcash-fpga#8]
Hi Ben,

I would like to know, in your estimation, what would be the theoretical maximum prover throughput if I tiled a large FPGA (like an Alveo 280) with the BLS12-381 coprocessors. LUT utilisation was 25% on your device (VU9P), so I assume I could get 3-4 processors on an equivalent device, leading to a 12x speedup against a pretty high-end CPU (3.7GHz!). I noticed the clock speed is quite low (200MHz) even for an FPGA design (could probably hit 275 MHz?). Is there a possibility of cranking this up? 

In your talk (https://www.youtube.com/watch?v=VNClWrMbhlg&t=1717s), is the CPU throughput referenced for single-thread or multiple threads? If it is single-thread, that is somewhat disappointing, since if I had 4 threads I should be able to achieve the same throughput.

Furthermore, judging by some past results, it seems one could get similar speedups (10x-40x) on a GPU? So perhaps FPGAs are not worth the trouble for now? Furthermore, how much could a powerful multicore machine like a threadripper with 64 or 128 logical threads do to speed things up over the CPU benchmark you used? This is assuming one could be running multiple proofs/pairings in parallel alongside parallelising individual proofs/pairings.

Best,
Jonathan

**Comment by bsdevlin** [comment]
I think with some optimizations for timing you could get the clock speed up to 250-300MHz.
In the talk the comparisons were on a single thread.
I haven't done comparison to GPU, but in general you should be able to get a better improvement from an FPGA due to being able to increase the number of parallel pairing coprocessors.
